#!/bin/bash -l

#PBS -N MHD_TEST

#PBS -q default

#PBS -l nodes=4:ppn=16

#PBS -l feature='ib1'

#PBS -l walltime=120:00:00

#PBS -A Rogers

#PBS -m bea

#PBS -M Ben.Zhu.GR@dartmouth.edu

#cd /ihome/bzhu/code/mhd/fortran/test/otv/
cd $PBS_O_WORKDIR

module unload intel-compilers/13.0

#>>>>>>>>>openmpi
module load intel-compilers/15.0
module load openmpi/1.6.5-intel15.0
module load hdf5/1.8.14-openmpi1.6.5-intel15.0

make -f makefile -W mhd3d2.f90

mpirun -np 64 ./mhd3d2.x

exit 0

